### PR TITLE
fix(Patches): quick hotfix, fix crashes

### PR DESCRIPTION
**Pull request by FlashHit**

### CODE REVIEW

**Comment by IllustrisJack** [comment]
big bruh moment

**Comment by IllustrisJack** [comment]
@GreatApo look at this 😂

**Comment by GreatApo** [comment]
> @GreatApo look at this 😂 

?

**Comment by IllustrisJack** [comment]
@GreatApo since we implemented this https://github.com/BF3RM/VEManager/commit/2424a9b949a93c449a981db63633acaefd17c72f we broke RM. Big RIP on our side. Basically i didn´t notice this since October ...

**Pull request merged**
